name: "Traffmonetizer - amd64"
slug: "traffmonetizer-amd64"
description: "Share your internet connection and make money online"
version: "1.0"
init: false
legacy: true
arch:
  - amd64
options:
  token: ""
  device-name: ""
schema:
  token: str
  device-name: str
