name: "Playitgg"
slug: "playitgg"
description: "Playit.gg is a global proxy that allows anyone to host a server without port forwarding. We use tunneling. Only the server needs to run the program, not every player"
init: false
legacy: true
arch:
  - aarch64
  - amd64
version: "0.15"
image: ghcr.io/playit-cloud/playit-agent
host_network: true
options:
  SECRET_KEY: ""
schema:
  SECRET_KEY: str
